sudo: false
language: node_js
env:
  - NODE_ENV=travis_mysql_test DB=mysql
services:
  - mysql

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - mysql -e 'CREATE DATABASE myapp_test;'

os:
  - linux

node_js:
  - "7"
  - "6"