sudo: false
language: node_js
env:
  - NODE_ENV=test DB=mysql
services:
  - mysql

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - if [[ "$DB" == "mysql" ]]; then npm install mysql; fi
  - if [[ "$DB" == "mysql" ]]; then cp test/config_files/local.test_mysql.yaml.travis config/local.test.json; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'CREATE DATABASE uptime2tests CHARACTER SET utf8 COLLATE utf8_bin;'; fi
  
script:
  - npm travis
os:
  - linux

node_js:
  - "7"
  - "6"